version: '3.9'

services:

  server:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./lamp:/var/www/html
      - ./cert:/etc/letsencrypt
      - ./config/nginx:/etc/nginx/conf.d/
      - ./log/nginx:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: core-php
    image: lemp-php-ext
    restart: unless-stopped
    volumes:
      - ./lamp:/var/www/html
      # - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db

  web-symfony:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-symfony
    environment:
      MARIADB_HOST: db4free.net
      MARIADB_PORT_NUMBER: 3306
      MARIADB_USER: adanfj
      MARIADB_PASSWORD: 1q2w3e4r5t6y
      MARIADB_DATABASE: symfony
    volumes:
      - ./lamp:/var/www/html
      - ./config/symfony/prod/.env:/var/www/html/symfony/.env
    # ports:
    #   - 8000:8000

