version: '3.9'

services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./lamp:/var/www/html
      - ./cert:/etc/letsencrypt
      - ./config/nginx:/etc/nginx/conf.d/
      - ./log/nginx:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: core-php
    image: lemp-php-ext
    restart: unless-stopped
    volumes:
      - ./lamp:/var/www/html
      # - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  web-symfony:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-symfony
    volumes:
      - ./lamp:/var/www/html
      - ./config/symfony/prod/.env:/var/www/html/symfony/.env

volumes:
  db:
  mysql:
