<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3G5hOx3\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3G5hOx3/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3G5hOx3.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container3G5hOx3\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container3G5hOx3\appAppKernelDevDebugContainer([
    'container.build_hash' => '3G5hOx3',
    'container.build_id' => '32f2da41',
    'container.build_time' => 1677956954,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3G5hOx3');
